Document: remnux-msoffice-crypt
Title: Debian remnux-msoffice-crypt Manual
Author: <insert document author here>
Abstract: This manual describes what remnux-msoffice-crypt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/remnux-msoffice-crypt/remnux-msoffice-crypt.sgml.gz

Format: postscript
Files: /usr/share/doc/remnux-msoffice-crypt/remnux-msoffice-crypt.ps.gz

Format: text
Files: /usr/share/doc/remnux-msoffice-crypt/remnux-msoffice-crypt.text.gz

Format: HTML
Index: /usr/share/doc/remnux-msoffice-crypt/html/index.html
Files: /usr/share/doc/remnux-msoffice-crypt/html/*.html
