#!/bin/bash

if [ ! `which java` ]; then
  echo "Java runtime environment is not installed."
  echo "Please install the 'default-jre' package."
  echo "Exiting."
  exit 1
fi

if [ ! -f /opt/jd-gui-files/jd-gui.jar ]; then
  echo "Cannot locate the JD GUI jar file. Exiting."
  exit 2
fi

java -jar /opt/jd-gui-files/jd-gui.jar ${*}

