#!/bin/bash

if [ ! `which java` ]; then
  echo "Java runtime environment is not installed."
  echo "Please install the 'default-jre' package."
  echo "Exiting."
  exit 1
fi

if [ ! -f /opt/burpsuite-community/burpsuite-community.jar ]; then
  echo "Cannot locate the Burp Suite Community Edition jar file. Exiting."
  exit 2
fi

java -jar /opt/burpsuite-community/burpsuite-community.jar ${*}

