#!/bin/bash

if [ ! `which java` ]; then
  echo "Java runtime environment is not installed."
  echo "Please install the 'default-jre' package."
  echo "Exiting."
  exit 1
fi

if [ ! -f /opt/AndroidProjectCreator-1.5.2-stable-jar-with-dependencies.jar ]; then
  echo "Cannot locate the ndroidProjectCreator jar file. Exiting."
  exit 2
fi

export JAVA_HOME=/usr/lib/jvm/default-java
java -jar /opt/AndroidProjectCreator/AndroidProjectCreator-1.5.2-stable-jar-with-dependencies.jar "$@"
