#!/bin/bash

#
# Determine the name of the active network interface.
# By default, show the name of the first active interface.
# With -a (or --all), list the names of all active interfaces.
#
# By Lenny Zeltser
#
# Public Domain
#

# Show the names of all active network interfaces
function mynic_all {
  ip addr | egrep -A 1 " (en|eth)" | grep UP | cut -f 2 -d " " | cut -f 1 -d ":" | cut -f 1 -d "@"
}

if [ "$1" = "-a" ] || [ "$1" = "--all" ]; then
  mynic_all
else
  mynic_all | head -n 1
fi
