tmpl = r'''<?xml version="1.0" encoding="shift_jis"?>
<VisualStudioProject
	ProjectType="Visual C++"
	Version="9.00"
	Name="@{ROOT_NAMESPACE}"
	ProjectGUID="@{PROJECT_GUID}"
	RootNamespace="@{ROOT_NAMESPACE}"
	Keyword="Win32Proj"
	TargetFrameworkVersion="196613"
	>
	<Platforms>
		<Platform
			Name="Win32"
		/>
		<Platform
			Name="x64"
		/>
	</Platforms>
	<ToolFiles>
	</ToolFiles>
	<Configurations>
		<Configuration
			Name="Debug|Win32"
			OutputDirectory="$(SolutionDir)$(ConfigurationName)"
			IntermediateDirectory="$(ConfigurationName)\@{ROOT_NAMESPACE}"
			ConfigurationType="@{CONFIGURATION_TYPE}"
			InheritedPropertySheets="@{INHERITED_PROPERTY_SHEETS_D}"
			CharacterSet="2"
			>
			<Tool
				Name="VCCLCompilerTool"
				Optimization="0"
				AdditionalIncludeDirectories="@{ADDITIONAL_INCLUDE_DIRECTORIES}"
				PreprocessorDefinitions="@{PREPROCESSOR_DEFINITIONS_D}"
				MinimalRebuild="true"
				BasicRuntimeChecks="3"
				RuntimeLibrary="3"
				UsePrecompiledHeader="0"
				DebugInformationFormat="4"
			/>
			<Tool
				Name="VCLinkerTool"
				OutputFile="@{OUTPUT_FILE_D}"
				AdditionalLibraryDirectories="@{ADDITIONAL_LIBRARY_DERECTORIES}"
				LinkIncremental="2"
				GenerateDebugInformation="true"
				SubSystem="1"
				TargetMachine="1"
			/>
			<Tool
				Name="VCLibrarianTool"
				OutputFile="@{OUTPUT_FILE_D}"
			/>
		</Configuration>
		<Configuration
			Name="Release|Win32"
			OutputDirectory="$(SolutionDir)$(ConfigurationName)"
			IntermediateDirectory="$(ConfigurationName)\@{ROOT_NAMESPACE}"
			ConfigurationType="@{CONFIGURATION_TYPE}"
			InheritedPropertySheets="@{INHERITED_PROPERTY_SHEETS}"
			CharacterSet="2"
			WholeProgramOptimization="1"
			>
			<Tool
				Name="VCCLCompilerTool"
				Optimization="2"
				EnableIntrinsicFunctions="true"
				AdditionalIncludeDirectories="@{ADDITIONAL_INCLUDE_DIRECTORIES}"
				PreprocessorDefinitions="@{PREPROCESSOR_DEFINITIONS}"
				RuntimeLibrary="2"
				EnableFunctionLevelLinking="true"
				UsePrecompiledHeader="0"
				DebugInformationFormat="3"
			/>
			<Tool
				Name="VCLibrarianTool"
				OutputFile="@{OUTPUT_FILE}"
			/>
			<Tool
				Name="VCLinkerTool"
				OutputFile="@{OUTPUT_FILE}"
				AdditionalLibraryDirectories="@{ADDITIONAL_LIBRARY_DERECTORIES}"
				LinkIncremental="1"
				GenerateDebugInformation="true"
				SubSystem="1"
				OptimizeReferences="2"
				EnableCOMDATFolding="2"
				TargetMachine="1"
			/>
		</Configuration>
		<Configuration
			Name="Debug|x64"
			OutputDirectory="$(SolutionDir)$(PlatformName)$(ConfigurationName)"
			IntermediateDirectory="$(ConfigurationName)\$(RootNamespace)64"
			ConfigurationType="@{CONFIGURATION_TYPE}"
			InheritedPropertySheets="@{INHERITED_PROPERTY_SHEETS_D}"
			CharacterSet="2"
			>
			<Tool
				Name="VCMIDLTool"
				TargetEnvironment="3"
			/>
			<Tool
				Name="VCCLCompilerTool"
				Optimization="0"
				AdditionalIncludeDirectories="@{ADDITIONAL_INCLUDE_DIRECTORIES}"
				PreprocessorDefinitions="@{PREPROCESSOR_DEFINITIONS_D}"
				MinimalRebuild="true"
				BasicRuntimeChecks="3"
				RuntimeLibrary="3"
				UsePrecompiledHeader="0"
				DebugInformationFormat="3"
			/>
			<Tool
				Name="VCLinkerTool"
				OutputFile="@{OUTPUT_FILE_D}"
				AdditionalLibraryDirectories="@{ADDITIONAL_LIBRARY_DERECTORIES}"
				LinkIncremental="2"
				GenerateDebugInformation="true"
				SubSystem="1"
				TargetMachine="17"
			/>
			<Tool
				Name="VCLibrarianTool"
				OutputFile="@{OUTPUT_FILE_D}"
			/>
		</Configuration>
		<Configuration
			Name="Release|x64"
			OutputDirectory="$(SolutionDir)$(PlatformName)$(ConfigurationName)"
			IntermediateDirectory="$(ConfigurationName)\$(RootNamespace)64"
			ConfigurationType="@{CONFIGURATION_TYPE}"
			InheritedPropertySheets="@{INHERITED_PROPERTY_SHEETS}"
			CharacterSet="2"
			WholeProgramOptimization="1"
			>
			<Tool
				Name="VCMIDLTool"
				TargetEnvironment="3"
			/>
			<Tool
				Name="VCCLCompilerTool"
				Optimization="2"
				EnableIntrinsicFunctions="true"
				AdditionalIncludeDirectories="@{ADDITIONAL_INCLUDE_DIRECTORIES}"
				PreprocessorDefinitions="@{PREPROCESSOR_DEFINITIONS}"
				RuntimeLibrary="2"
				EnableFunctionLevelLinking="true"
				UsePrecompiledHeader="0"
				DebugInformationFormat="3"
			/>
			<Tool
				Name="VCLibrarianTool"
				OutputFile="@{OUTPUT_FILE}"
			/>
			<Tool
				Name="VCLinkerTool"
				OutputFile="@{OUTPUT_FILE}"
				AdditionalLibraryDirectories="@{ADDITIONAL_LIBRARY_DERECTORIES}"
				LinkIncremental="1"
				GenerateDebugInformation="true"
				SubSystem="1"
				OptimizeReferences="2"
				EnableCOMDATFolding="2"
				TargetMachine="17"
			/>
		</Configuration>
	</Configurations>
	<References>
	</References>
	<Files>
		<Filter
			Name="Source Files"
			Filter="cpp;c;cc;cxx">
			@{SOURCE_FILE}
		</Filter>
		<Filter
			Name="Header Files"
			Filter="h;hpp">
		</Filter>
	</Files>
	<Globals>
	</Globals>
</VisualStudioProject>
'''
