#!/bin/bash

if [ ! `which java` ]; then
  echo "Java runtime environment is not installed."
  echo "Please install the 'default-jre' package."
  echo "Exiting."
  exit 1
fi

if [ ! -f /opt/baksmali/baksmali-2.4.0.jar ]; then
  echo "Cannot locate the baksmali jar file. Exiting."
  exit 2
fi

java -jar /opt/baksmali/baksmali-2.4.0.jar ${*}
